export type Genre = "Hip hop" | "New jack swing" | "Rave";
export type Artist = {
  id: string;
  name: string;
  genre: Genre;
  years: string;
  hometown: string;
  bio: string;
  color: string;
  songs: string[];
};

// Curated listening essentials, not Spotify popularity rankings. Search links
// deliberately avoid inventing Spotify track IDs or claiming API retrieval.
export const artists: Artist[] = [
  {
    id: "tribe",
    name: "A Tribe Called Quest",
    genre: "Hip hop",
    years: "1988–1998",
    hometown: "Queens, NYC",
    color: "#d7ff39",
    bio: "Queens innovators who made jazz samples, conversational rhymes, and loose-limbed drums feel like a new language. The Low End Theory and Midnight Marauders are essential early-90s listening.",
    songs: [
      "Can I Kick It?",
      "Check the Rhime",
      "Scenario",
      "Award Tour",
      "Electric Relaxation",
      "Bonita Applebum",
      "Jazz (We've Got)",
      "Oh My God",
      "Buggin' Out",
      "I Left My Wallet in El Segundo",
    ],
  },
  {
    id: "de-la",
    name: "De La Soul",
    genre: "Hip hop",
    years: "1989–1993",
    hometown: "Long Island, NY",
    color: "#ffafdf",
    bio: "Posdnuos, Trugoy, and Maseo brought playful sampling and offbeat storytelling to the Native Tongues movement. Their colorful debut gave way to the sharper edges of De La Soul Is Dead and Buhloone Mindstate.",
    songs: [
      "Me Myself and I",
      "The Magic Number",
      "Eye Know",
      "Buddy",
      "Potholes in My Lawn",
      "A Roller Skating Jam Named 'Saturdays'",
      "Ring Ring Ring (Ha Ha Hey)",
      "Breakadawn",
      "Ego Trippin' (Part Two)",
      "Stakes Is High",
    ],
  },
  {
    id: "wu-tang",
    name: "Wu-Tang Clan",
    genre: "Hip hop",
    years: "1993–1997",
    hometown: "Staten Island, NYC",
    color: "#ffc347",
    bio: "A Staten Island collective whose raw beats, kung-fu samples, and distinct MC voices transformed New York rap. Enter the Wu-Tang (36 Chambers) made an underground crew into a cultural force.",
    songs: [
      "C.R.E.A.M.",
      "Protect Ya Neck",
      "Method Man",
      "Da Mystery of Chessboxin'",
      "Wu-Tang Clan Ain't Nuthing ta F' Wit",
      "Can It Be All So Simple",
      "Bring da Ruckus",
      "Shame on a Nigga",
      "Triumph",
      "Reunited",
    ],
  },
  {
    id: "nas",
    name: "Nas",
    genre: "Hip hop",
    years: "1994–1996",
    hometown: "Queensbridge, NYC",
    color: "#88d7ff",
    bio: "A Queensbridge storyteller whose debut Illmatic turns city blocks into vivid scenes. His tightly observed writing and jazz-rooted production remain a defining snapshot of 90s New York.",
    songs: [
      "N.Y. State of Mind",
      "The World Is Yours",
      "Life's a Bitch",
      "It Ain't Hard to Tell",
      "One Love",
      "Memory Lane (Sittin' in da Park)",
      "Halftime",
      "Represent",
      "Street Dreams",
      "If I Ruled the World (Imagine That)",
    ],
  },
  {
    id: "guy",
    name: "Guy",
    genre: "New jack swing",
    years: "1988–1990",
    hometown: "Harlem, NYC",
    color: "#ffafdf",
    bio: "Teddy Riley, Aaron Hall, and Damion Hall helped define new jack swing: gospel-trained R&B vocals riding sharply programmed hip-hop drums. Guy and The Future are the movement's dance-floor blueprints.",
    songs: [
      "Groove Me",
      "Teddy's Jam",
      "I Like",
      "Piece of My Love",
      "Let's Chill",
      "Do Me Right",
      "D-O-G Me Out",
      "Wanna Get With U",
      "My Fantasy",
      "Goodbye Love",
    ],
  },
  {
    id: "bell-biv",
    name: "Bell Biv DeVoe",
    genre: "New jack swing",
    years: "1990–1993",
    hometown: "Boston, MA",
    color: "#d7ff39",
    bio: "New Edition alumni Ricky Bell, Michael Bivins, and Ronnie DeVoe mixed R&B harmonies with rap attitude. Poison captured the crossover energy of the turn of the decade.",
    songs: [
      "Poison",
      "Do Me!",
      "B.B.D. (I Thought It Was Me)?",
      "When Will I See You Smile Again?",
      "She's Dope!",
      "Dope!",
      "Let's Get the Party Started",
      "Something in Your Eyes",
      "Above the Rim",
      "Gangsta",
    ],
  },
  {
    id: "janet",
    name: "Janet Jackson",
    genre: "New jack swing",
    years: "1989–1993",
    hometown: "Gary, IN",
    color: "#88d7ff",
    bio: "With Jimmy Jam and Terry Lewis, Jackson paired precision choreography and socially conscious pop with propulsive R&B. Rhythm Nation 1814 and janet. connect industrial-strength grooves to intimacy.",
    songs: [
      "Rhythm Nation",
      "Miss You Much",
      "Escapade",
      "Alright",
      "Love Will Never Do (Without You)",
      "Black Cat",
      "State of the World",
      "That's the Way Love Goes",
      "If",
      "Any Time, Any Place",
    ],
  },
  {
    id: "prodigy",
    name: "The Prodigy",
    genre: "Rave",
    years: "1991–1997",
    hometown: "Braintree, England",
    color: "#ffc347",
    bio: "Liam Howlett's breakbeats, chopped vocals, and rave hooks pushed UK dance music toward punk intensity. Experience and Music for the Jilted Generation trace that shift from warehouse to main stage.",
    songs: [
      "Charly",
      "Everybody in the Place",
      "Out of Space",
      "Your Love",
      "Wind It Up",
      "No Good (Start the Dance)",
      "Voodoo People",
      "Poison",
      "Firestarter",
      "Breathe",
    ],
  },
  {
    id: "orbital",
    name: "Orbital",
    genre: "Rave",
    years: "1989–1996",
    hometown: "Sevenoaks, England",
    color: "#ffafdf",
    bio: "Brothers Phil and Paul Hartnoll built patient, melodic electronic journeys from the UK rave scene. Their live approach and luminous synth patterns made dance music feel expansive and emotional.",
    songs: [
      "Chime",
      "Belfast",
      "Halcyon and On and On",
      "Lush 3-1",
      "Lush 3-2",
      "Impact (The Earth Is Burning)",
      "Remind",
      "Satan",
      "The Box",
      "Are We Here?",
    ],
  },
  {
    id: "808",
    name: "808 State",
    genre: "Rave",
    years: "1988–1993",
    hometown: "Manchester, England",
    color: "#d7ff39",
    bio: "Manchester electronic pioneers at the intersection of acid house, techno, and club experimentation. Pacific State's saxophone and synths became a signature sound of the UK dance explosion.",
    songs: [
      "Pacific State",
      "Cubik",
      "In Yer Face",
      "Olympic",
      "One in Ten",
      "Lift",
      "Ooops",
      "San Francisco",
      "Plan 9",
      "Niagara",
    ],
  },
];

export function spotifySearch(artist: string, song: string) {
  return `https://open.spotify.com/search/${encodeURIComponent(`${artist} ${song}`)}`;
}

export function getDailyArtist() {
  return artists[Math.floor(Date.now() / 86400000) % artists.length];
}
