export const genres = [
  "Hip hop",
  "New jack swing",
  "R&B",
  "Techno",
  "Rave",
  "Eurodance",
  "Eurobeat / Hi-NRG",
] as const;
export type Genre = (typeof genres)[number];
export type Artist = {
  id: string;
  name: string;
  genre: Genre;
  years: string;
  hometown: string;
  bio: string;
  color: string;
  songs: string[];
  trackPlatform?: "youtube" | "spotify";
};

// Curated listening essentials, not Spotify popularity rankings. Search links
// deliberately avoid inventing Spotify track IDs or claiming API retrieval.
export const artists: Artist[] = [
  {
    id: "tribe",
    name: "A Tribe Called Quest",
    genre: "Hip hop",
    years: "1988–1998",
    hometown: "Queens, NYC",
    color: "#d7ff39",
    bio: "Queens innovators who made jazz samples, conversational rhymes, and loose-limbed drums feel like a new language. The Low End Theory and Midnight Marauders are essential early-90s listening.",
    songs: [
      "Can I Kick It?",
      "Check the Rhime",
      "Scenario",
      "Award Tour",
      "Electric Relaxation",
      "Bonita Applebum",
      "Jazz (We've Got)",
      "Oh My God",
      "Buggin' Out",
      "I Left My Wallet in El Segundo",
    ],
  },
  {
    id: "de-la",
    name: "De La Soul",
    genre: "Hip hop",
    years: "1989–1993",
    hometown: "Long Island, NY",
    color: "#ffafdf",
    bio: "Posdnuos, Trugoy, and Maseo brought playful sampling and offbeat storytelling to the Native Tongues movement. Their colorful debut gave way to the sharper edges of De La Soul Is Dead and Buhloone Mindstate.",
    songs: [
      "Me Myself and I",
      "The Magic Number",
      "Eye Know",
      "Buddy",
      "Potholes in My Lawn",
      "A Roller Skating Jam Named 'Saturdays'",
      "Ring Ring Ring (Ha Ha Hey)",
      "Breakadawn",
      "Ego Trippin' (Part Two)",
      "Stakes Is High",
    ],
  },
  {
    id: "wu-tang",
    name: "Wu-Tang Clan",
    genre: "Hip hop",
    years: "1993–1997",
    hometown: "Staten Island, NYC",
    color: "#ffc347",
    bio: "A Staten Island collective whose raw beats, kung-fu samples, and distinct MC voices transformed New York rap. Enter the Wu-Tang (36 Chambers) made an underground crew into a cultural force.",
    songs: [
      "C.R.E.A.M.",
      "Protect Ya Neck",
      "Method Man",
      "Da Mystery of Chessboxin'",
      "Wu-Tang Clan Ain't Nuthing ta F' Wit",
      "Can It Be All So Simple",
      "Bring da Ruckus",
      "Shame on a Nigga",
      "Triumph",
      "Reunited",
    ],
  },
  {
    id: "nas",
    name: "Nas",
    genre: "Hip hop",
    years: "1994–1996",
    hometown: "Queensbridge, NYC",
    color: "#88d7ff",
    bio: "A Queensbridge storyteller whose debut Illmatic turns city blocks into vivid scenes. His tightly observed writing and jazz-rooted production remain a defining snapshot of 90s New York.",
    songs: [
      "N.Y. State of Mind",
      "The World Is Yours",
      "Life's a Bitch",
      "It Ain't Hard to Tell",
      "One Love",
      "Memory Lane (Sittin' in da Park)",
      "Halftime",
      "Represent",
      "Street Dreams",
      "If I Ruled the World (Imagine That)",
    ],
  },
  {
    id: "guy",
    name: "Guy",
    genre: "New jack swing",
    years: "1988–1990",
    hometown: "Harlem, NYC",
    color: "#ffafdf",
    bio: "Teddy Riley, Aaron Hall, and Damion Hall helped define new jack swing: gospel-trained R&B vocals riding sharply programmed hip-hop drums. Guy and The Future are the movement's dance-floor blueprints.",
    songs: [
      "Groove Me",
      "Teddy's Jam",
      "I Like",
      "Piece of My Love",
      "Let's Chill",
      "Do Me Right",
      "D-O-G Me Out",
      "Wanna Get With U",
      "My Fantasy",
      "Goodbye Love",
    ],
  },
  {
    id: "bell-biv",
    name: "Bell Biv DeVoe",
    genre: "New jack swing",
    years: "1990–1993",
    hometown: "Boston, MA",
    color: "#d7ff39",
    bio: "New Edition alumni Ricky Bell, Michael Bivins, and Ronnie DeVoe mixed R&B harmonies with rap attitude. Poison captured the crossover energy of the turn of the decade.",
    songs: [
      "Poison",
      "Do Me!",
      "B.B.D. (I Thought It Was Me)?",
      "When Will I See You Smile Again?",
      "She's Dope!",
      "Dope!",
      "Let's Get the Party Started",
      "Something in Your Eyes",
      "Above the Rim",
      "Gangsta",
    ],
  },
  {
    id: "janet",
    name: "Janet Jackson",
    genre: "New jack swing",
    years: "1989–1993",
    hometown: "Gary, IN",
    color: "#88d7ff",
    bio: "With Jimmy Jam and Terry Lewis, Jackson paired precision choreography and socially conscious pop with propulsive R&B. Rhythm Nation 1814 and janet. connect industrial-strength grooves to intimacy.",
    songs: [
      "Rhythm Nation",
      "Miss You Much",
      "Escapade",
      "Alright",
      "Love Will Never Do (Without You)",
      "Black Cat",
      "State of the World",
      "That's the Way Love Goes",
      "If",
      "Any Time, Any Place",
    ],
  },
  {
    id: "prodigy",
    name: "The Prodigy",
    genre: "Rave",
    years: "1991–1997",
    hometown: "Braintree, England",
    color: "#ffc347",
    bio: "Liam Howlett's breakbeats, chopped vocals, and rave hooks pushed UK dance music toward punk intensity. Experience and Music for the Jilted Generation trace that shift from warehouse to main stage.",
    songs: [
      "Charly",
      "Everybody in the Place",
      "Out of Space",
      "Your Love",
      "Wind It Up",
      "No Good (Start the Dance)",
      "Voodoo People",
      "Poison",
      "Firestarter",
      "Breathe",
    ],
  },
  {
    id: "orbital",
    name: "Orbital",
    genre: "Rave",
    years: "1989–1996",
    hometown: "Sevenoaks, England",
    color: "#ffafdf",
    bio: "Brothers Phil and Paul Hartnoll built patient, melodic electronic journeys from the UK rave scene. Their live approach and luminous synth patterns made dance music feel expansive and emotional.",
    songs: [
      "Chime",
      "Belfast",
      "Halcyon and On and On",
      "Lush 3-1",
      "Lush 3-2",
      "Impact (The Earth Is Burning)",
      "Remind",
      "Satan",
      "The Box",
      "Are We Here?",
    ],
  },
  {
    id: "808",
    name: "808 State",
    genre: "Rave",
    years: "1988–1993",
    hometown: "Manchester, England",
    color: "#d7ff39",
    bio: "Manchester electronic pioneers at the intersection of acid house, techno, and club experimentation. Pacific State's saxophone and synths became a signature sound of the UK dance explosion.",
    songs: [
      "Pacific State",
      "Cubik",
      "In Yer Face",
      "Olympic",
      "One in Ten",
      "Lift",
      "Ooops",
      "San Francisco",
      "Plan 9",
      "Niagara",
    ],
  },
  {
    id: "tlc",
    name: "TLC",
    genre: "R&B",
    years: "1992–1999",
    hometown: "Atlanta, GA",
    color: "#ffafdf",
    bio: "T-Boz, Left Eye, and Chilli turned playful rap, rich harmonies, and outspoken style into a defining Atlanta sound. Their 90s records move from the colorful new jack swing of Ooooooohhh... On the TLC Tip to the smooth edges of CrazySexyCool and FanMail.",
    songs: [
      "Ain't 2 Proud 2 Beg",
      "Baby-Baby-Baby",
      "What About Your Friends",
      "Hat 2 da Back",
      "Creep",
      "Red Light Special",
      "Waterfalls",
      "Diggin' on You",
      "No Scrubs",
      "Unpretty",
    ],
  },
  {
    id: "xscape",
    name: "Xscape",
    genre: "R&B",
    years: "1993–1998",
    hometown: "Atlanta, GA",
    color: "#88d7ff",
    bio: "Atlanta's Kandi Burruss, Tameka Scott, LaTocha Scott, and Tameka Cottle brought gospel-strength harmonies to hip-hop soul. Their three 90s albums balance hard drums, candid storytelling, and slow jams that still fill a room.",
    songs: [
      "Just Kickin' It",
      "Understanding",
      "Love on My Mind",
      "Tonight",
      "Who Can I Run To",
      "Do You Want To",
      "Can't Hang",
      "The Arms of the One Who Loves You",
      "My Little Secret",
      "Softest Place on Earth",
    ],
  },
  {
    id: "swv",
    name: "SWV",
    genre: "R&B",
    years: "1992–1997",
    hometown: "New York, NY",
    color: "#ffc347",
    bio: "Sisters With Voices—Coko, Taj, and Lelee—made New York's hip-hop soul feel both tender and streetwise. Their layered harmonies connect the breakthroughs on It's About Time to the spacious grooves of New Beginning and Release Some Tension.",
    songs: [
      "Weak",
      "Right Here",
      "I'm So into You",
      "Downtown",
      "Anything",
      "You're the One",
      "Use Your Heart",
      "Rain",
      "Someone",
      "Can We",
    ],
  },
  {
    id: "en-vogue",
    name: "En Vogue",
    genre: "R&B",
    years: "1990–1997",
    hometown: "Oakland, CA",
    color: "#d7ff39",
    bio: "Oakland's vocal quartet paired classic girl-group precision with modern R&B production and striking visual style. Born to Sing and Funky Divas made four-part harmony sound powerful, playful, and ready for the dance floor.",
    songs: [
      "Hold On",
      "Lies",
      "You Don't Have to Worry",
      "Don't Go",
      "My Lovin' (You're Never Gonna Get It)",
      "Giving Him Something He Can Feel",
      "Free Your Mind",
      "Give It Up, Turn It Loose",
      "Don't Let Go (Love)",
      "Whatever",
    ],
  },
  {
    id: "jodeci",
    name: "Jodeci",
    genre: "R&B",
    years: "1991–1995",
    hometown: "Charlotte, NC",
    color: "#ffafdf",
    bio: "North Carolina brothers DeVante Swing and Mr. Dalvin joined brothers K-Ci and JoJo to give R&B a rougher silhouette. Gospel-rooted singing, hip-hop attitude, and DeVante's production made their early albums landmarks of 90s slow jams.",
    songs: [
      "Forever My Lady",
      "Stay",
      "Come & Talk to Me",
      "I'm Still Waiting",
      "U & I",
      "Cry for You",
      "Feenin'",
      "My Heart Belongs to U",
      "Freek'n You",
      "Love U 4 Life",
    ],
  },
  {
    id: "hi-five",
    name: "Hi-Five",
    genre: "New jack swing",
    years: "1990–1993",
    hometown: "Waco, TX",
    color: "#88d7ff",
    bio: "This Texas-rooted vocal group brought bright harmonies and teenage romance to new jack swing, with Tony Thompson's unmistakable lead at the center. Their early hits keep the drums crisp and the melodies immediately singable.",
    songs: [
      "I Like the Way (The Kissing Game)",
      "I Can't Wait Another Minute",
      "Just Another Girlfriend",
      "She's Playing Hard to Get",
      "Quality Time",
      "Unconditional Love",
      "Never Should've Let You Go",
      "Faithful",
      "Mary, Mary",
      "Rags to Riches",
    ],
  },
  // Album and compilation tracklists: https://en.wikipedia.org/wiki/L.A._Boyz
  {
    id: "la-boyz",
    name: "L.A. Boyz",
    genre: "New jack swing",
    years: "1992–1997",
    hometown: "Irvine, CA / Taiwan",
    color: "#ffafdf",
    bio: "Taiwanese-American brothers Jeffrey and Stanley Huang joined cousin Steven Lin to bring Mandarin rap, athletic dancing, and new jack swing to Taiwan. These ten YouTube listening essentials introduce a group whose cross-Pacific energy made them a defining 90s act.",
    trackPlatform: "youtube",
    songs: [
      "YA!",
      "Shiam (閃)",
      "That's The Way (就是這樣)",
      "JUMP (跳)",
      "Fantasy",
      "Young Guns",
      "交換禮物",
      "R.O.C.K.",
      "Pure Energy",
      "Baseball, O-Lay!!",
    ],
  },
  // Album/single titles: https://en.wikipedia.org/wiki/Express_Yourself_Clearly
  // Later singles: https://en.wikipedia.org/wiki/E.Y.C._(band)
  {
    id: "eyc",
    name: "EYC",
    genre: "New jack swing",
    years: "1993–1999",
    hometown: "Los Angeles, CA",
    color: "#ffc347",
    bio: "Express Yourself Clearly joined Damon Butler, David Loeffler, and Trey Parker in a Los Angeles pop/R&B trio. Their debut album Express Yourself Clearly and single Get Some bring new jack swing grooves and bright pop hooks to a group known for tight choreography and a strong UK following.",
    songs: [
      "Feelin' Alright",
      "The Way You Work It",
      "Black Book",
      "Number One",
      "One More Chance",
      "Ooh-Ah-Aa (I Feel It)",
      "This Thing Called Love",
      "Get Some",
      "Only a Dream",
      "You Are My Happiness",
    ],
  },
  {
    id: "bobby-brown",
    name: "Bobby Brown",
    genre: "New jack swing",
    years: "1986–1993",
    hometown: "Boston, MA",
    color: "#d7ff39",
    bio: "After New Edition, Brown helped take new jack swing into pop's center with swagger, athletic dancing, and sharp R&B hooks. Don't Be Cruel and Bobby capture the turn-of-the-decade blend of soulful vocals and programmed hip-hop drums.",
    songs: [
      "Don't Be Cruel",
      "My Prerogative",
      "Every Little Step",
      "Roni",
      "Rock Wit'cha",
      "On Our Own",
      "Humpin' Around",
      "Good Enough",
      "Get Away",
      "Girlfriend",
    ],
  },
  {
    id: "inner-city",
    name: "Inner City",
    genre: "Techno",
    years: "1988–1994",
    hometown: "Detroit, MI",
    color: "#88d7ff",
    bio: "Detroit producer Kevin Saunderson and singer Paris Grey connected techno's electronic pulse to joyful house vocals. Their crossover singles carry the city's machine soul into big choruses and communal dance-floor release.",
    songs: [
      "Big Fun",
      "Good Life",
      "Ain't Nobody Better",
      "Do You Love What You Feel",
      "Whatcha Gonna Do with My Lovin'",
      "That Man (He's All Mine)",
      "Hallelujah",
      "Till We Meet Again",
      "Back Together Again",
      "Pennies from Heaven",
    ],
  },
  {
    id: "underground-resistance",
    name: "Underground Resistance",
    genre: "Techno",
    years: "1990–2002",
    hometown: "Detroit, MI",
    color: "#ffc347",
    bio: "Detroit's collective and label, founded by Mike Banks and Jeff Mills, pairs uncompromising techno with a fiercely independent outlook. The selection follows its early records into later releases, tracing machine rhythms, futuristic jazz, and music as resistance.",
    songs: [
      "The Final Frontier",
      "Jupiter Jazz",
      "The Theory",
      "The Cosmic Traveler",
      "Deep Space 9",
      "Punisher",
      "Seawolf",
      "Riot",
      "Fury",
      "Transition",
    ],
  },
  {
    id: "mary-j-blige",
    name: "Mary J. Blige",
    genre: "R&B",
    years: "1992–1996",
    hometown: "Yonkers, NY",
    color: "#d7ff39",
    bio: "Raised in Yonkers, Blige put candid, gospel-rooted singing over hip-hop beats and helped define hip-hop soul. What's the 411? and My Life made vulnerability and street style part of the same conversation, influencing a generation of R&B artists.",
    songs: [
      "Real Love",
      "You Remind Me",
      "Reminisce",
      "Sweet Thing",
      "Love No Limit",
      "You Don't Have to Worry",
      "Be Happy",
      "I'm Goin' Down",
      "You Bring Me Joy",
      "Not Gon' Cry",
    ],
  },
  {
    id: "jeff-mills",
    name: "Jeff Mills",
    genre: "Techno",
    years: "1992–1997",
    hometown: "Detroit, MI",
    color: "#ffafdf",
    bio: "Detroit's former radio DJ The Wizard became a techno pioneer known for fast mixing and lean, propulsive production. His early solo releases and Purpose Maker records turn a few precise elements into an expansive dance-floor language.",
    songs: [
      "The Bells",
      "Alarms",
      "Phase 4",
      "Changes of Life",
      "Berlin",
      "The Extremist",
      "Man from Tomorrow",
      "DNA",
      "Life Cycle",
      "Waveform",
    ],
  },
  {
    id: "2-unlimited",
    name: "2 Unlimited",
    genre: "Eurodance",
    years: "1991–1994",
    hometown: "Amsterdam, Netherlands",
    color: "#d7ff39",
    bio: "Ray Slijngaard and Anita Doth fronted a Dutch-Belgian project whose rave synths, rap verses, and huge sung hooks became a 90s club blueprint. Their early singles favor direct, high-energy choruses built to travel across borders.",
    songs: [
      "Get Ready for This",
      "Twilight Zone",
      "Workaholic",
      "The Magic Friend",
      "No Limit",
      "Tribal Dance",
      "Faces",
      "Maximum Overdrive",
      "Let the Beat Control Your Body",
      "The Real Thing",
    ],
  },
  {
    id: "snap",
    name: "Snap!",
    genre: "Eurodance",
    years: "1990–1995",
    hometown: "Frankfurt, Germany",
    color: "#88d7ff",
    bio: "The Frankfurt production project fused heavy beats, rap, and commanding vocals into some of Eurodance's defining singles. From The Power to Rhythm Is a Dancer, the sound bridges early hip-house and the melodic rush of the European 90s.",
    songs: [
      "The Power",
      "Ooops Up",
      "Cult of Snap!",
      "Mary Had a Little Boy",
      "Colour of Love",
      "Rhythm Is a Dancer",
      "Exterminate!",
      "Do You See the Light (Looking For)",
      "Welcome to Tomorrow (Are You Ready?)",
      "The First the Last Eternity (Till the End)",
    ],
  },
  {
    id: "culture-beat",
    name: "Culture Beat",
    genre: "Eurodance",
    years: "1990–1996",
    hometown: "Frankfurt, Germany",
    color: "#ffc347",
    bio: "Founded by German producer Torsten Fenslau, Culture Beat brought rap verses and powerful sung hooks together over driving synths. Mr. Vain and its follow-ups capture Eurodance's bright, maximal energy without losing the club groove.",
    songs: [
      "Mr. Vain",
      "Got to Get It",
      "Anything",
      "World in Your Hands",
      "Inside Out",
      "Crying in the Rain",
      "Take Me Away",
      "Walk the Same Line",
      "I Like You",
      "No Deeper Meaning",
    ],
  },
  {
    id: "real-mccoy",
    name: "Real McCoy",
    genre: "Eurodance",
    years: "1993–1997",
    hometown: "Berlin, Germany",
    color: "#ffafdf",
    bio: "Built around Berlin rapper and songwriter Olaf 'O-Jay' Jeglitza, Real McCoy paired dance-pop melodies with brisk beats and rap. Another Night helped carry European club music into American radio while the group's albums kept the momentum going.",
    songs: [
      "Another Night",
      "Run Away",
      "Come and Get Your Love",
      "Automatic Lover (Call for Love)",
      "Love & Devotion",
      "Ooh Boy",
      "Sleeping with an Angel",
      "Tonight",
      "Operator",
      "One More Time",
    ],
  },
  {
    id: "dead-or-alive",
    name: "Dead or Alive",
    genre: "Eurobeat / Hi-NRG",
    years: "1984–1990",
    hometown: "Liverpool, England",
    color: "#d7ff39",
    bio: "Pete Burns's Liverpool band helped set the Hi-NRG foundations that fed into 90s dance-pop and Eurobeat. Dramatic vocals, sequenced bass, and relentless hooks make the 80s-to-90s bridge part of this collection's story.",
    songs: [
      "You Spin Me Round (Like a Record)",
      "Lover Come Back to Me",
      "In Too Deep",
      "My Heart Goes Bang (Get Me to the Doctor)",
      "Brand New Lover",
      "Something in My House",
      "I'll Save You All My Kisses",
      "Turn Around and Count 2 Ten",
      "Come Home with Me Baby",
      "Your Sweetness (Is Your Weakness)",
    ],
  },
  {
    id: "dave-rodgers",
    name: "Dave Rodgers",
    genre: "Eurobeat / Hi-NRG",
    years: "1991–2001",
    hometown: "Mantua, Italy",
    color: "#ffc347",
    bio: "Italian singer and producer Giancarlo Pasquini, also known through Aleph, helped shape Eurobeat and the A-Beat C label. These selections reach into the later Initial D era, where racing synths and oversized choruses found a new audience.",
    songs: [
      "Deja Vu",
      "Space Boy",
      "Beat of the Rising Sun",
      "Boom Boom Japan",
      "The Race Is Over",
      "Eldorado",
      "Kingdom of Rock",
      "Music for the People",
      "Take Me Higher",
      "Rich and Famous",
    ],
  },
  // Selected singles: https://en.wikipedia.org/wiki/Sinitta
  // Recording titles corroborated by MusicBrainz's Sinitta catalog.
  {
    id: "sinitta",
    name: "Sinitta",
    genre: "Eurobeat / Hi-NRG",
    years: "1986–1992",
    hometown: "Seattle, WA / London",
    color: "#88d7ff",
    bio: "Seattle-born, London-based singer Sinitta brought playful vocals and bold hooks to Hi-NRG and dance-pop. Her Stock Aitken Waterman hits and later dance-floor covers connect the late-80s club sound to the early 90s, adding a bright pop edge to the collection.",
    songs: [
      "Toy Boy",
      "So Macho",
      "Cross My Broken Heart",
      "GTO",
      "Right Back Where We Started From",
      "Love on a Mountain Top",
      "Hitchin' a Ride",
      "Shame Shame Shame",
      "Lay Me Down Easy",
      "I Don't Believe in Miracles",
    ],
  },
];

export function spotifySearch(artist: string, song: string) {
  return `https://open.spotify.com/search/${encodeURIComponent(`${artist} ${song}`)}`;
}

export function trackSearch(artist: Artist, song: string) {
  if (artist.trackPlatform === "youtube") {
    return `https://www.youtube.com/results?search_query=${encodeURIComponent(`${artist.name} ${song}`)}`;
  }
  return spotifySearch(artist.name, song);
}

export function trackPlatformLabel(artist: Artist) {
  return artist.trackPlatform === "youtube" ? "YouTube" : "Spotify";
}

export function getDailyArtist() {
  return artists[Math.floor(Date.now() / 86400000) % artists.length];
}
